spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace:
        ip:

    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        pool:
          max-connections: 2000
        connect-timeout: 3000
        response-timeout: 15000

      routes:
        - id: test
          uri: https://httpbin.org
          predicates:
            - Path=/test/{segment}
          filters:
            - SetPath=/{segment}



  application:
    name: gateway

server:
  port: 9000


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

publicKeyPem: |
  -----BEGIN PUBLIC KEY-----
  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElpzANDFRDkLNJ6Ee4iB9hogVXD56
  gNchXHXAnuYxLxuNPPBZDvtvMBUToT+L2UiUzusQJYo9oI86GH9NUqJCjQ==
  -----END PUBLIC KEY-----