spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace:
        ip:

    gateway:
      redis-rate-limiter:
        includeHeaders: false
      filter:
        request-rate-limiter:
          deny-empty-key: false
#          empty-key-status-code: 200
      default-filters:
        - name: RequestRateLimiter
          args:
            # 令牌桶每秒填充平均速率
            redis-rate-limiter.replenishRate: 15
            # 令牌桶的上限
            redis-rate-limiter.burstCapacity: 30
            redis-rate-limiter.requestedTokens: 1
            # 使用SpEL表达式从Spring容器中获取Bean对象
            key-resolver: "#{@tokenKeyResolver}"
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
#        - RemoveRequestHeader=Authorization
      discovery:
        locator:
          enabled: true
        include-expression: serviceId != 'paygate-business' and serviceId != 'service-d'
      globalcors:
        cors-configurations:
          '[/**]':
            maxAge: 3600
            allowedOrigins: "*"
            allowedHeaders: "Origin, X-Requested-With, Content-Type, Accept, Authorization, *"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      httpclient:
        pool:
          max-connections: 2000
        connect-timeout: 3000
        response-timeout: 15s

      routes:
        - id: test
          uri: https://httpbin.org
          predicates:
            - Path=/test/{segment}
          filters:
            - SetPath=/{segment}
        - id: host_route
          uri: http://prd-api:8112
          predicates:
            - Host=api.shwoody.com



  application:
    name: gateway
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 9000

management:
  endpoint:
    health:
      show-details: always

  health:
    nacosConfig:
      enabled: false
    nacosDiscovery:
      enabled: false